# Generated by Django 4.2.7 on 2024-04-11 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorizer_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Executor_Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RFC_Form',
            fields=[
                ('Rfc_Number', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('Reference_RFC_No', models.IntegerField(default=0)),
                ('Environment', models.CharField(max_length=100)),
                ('Planned_Date', models.DateField()),
                ('Reason_for_change', models.CharField(max_length=200)),
                ('Description_of_change', models.CharField(max_length=500)),
                ('Change_Requested_by', models.CharField(max_length=100)),
                ('Change_level', models.CharField(max_length=100)),
                ('Change_impact_assessment', models.CharField(max_length=200)),
                ('Risk_Rating', models.CharField(max_length=100)),
                ('Attachments', models.FileField(upload_to='Attachment')),
                ('Change_rollback_procedures', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('HOLD', 'HOLD'), ('CANCELLED', 'CANCELLED'), ('ROLLBACK', 'ROLLBACK'), ('CLOSED', 'CLOSED')], default='PENDING', max_length=100)),
                ('Activity_Notes', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Activity_Date', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('Change_authorizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authorizer_name')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
                ('Request_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.request_type')),
                ('System_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.system_details')),
                ('To_be_executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.executor_name')),
            ],
        ),
    ]
