# Generated by Django 4.2.7 on 2024-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizer_name',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='executor_name',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
