# Generated by Django 4.2.7 on 2024-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rfc_register_delete_rfc_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfc_register',
            name='Activity_Notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
