# Generated by Django 4.2.7 on 2024-04-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_rfc_register_activity_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfc_register',
            name='Activity_Date',
        ),
        migrations.RemoveField(
            model_name='rfc_register',
            name='Activity_Notes',
        ),
        migrations.RemoveField(
            model_name='rfc_register',
            name='status',
        ),
    ]
