# Generated by Django 4.2.7 on 2024-04-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_rfc_register_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfc_register',
            name='Activity_Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rfc_register',
            name='Activity_Notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rfc_register',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('HOLD', 'HOLD'), ('CANCELLED', 'CANCELLED'), ('ROLLBACK', 'ROLLBACK'), ('CLOSED', 'CLOSED')], max_length=100, null=True),
        ),
    ]
