# Generated by Django 4.2.7 on 2024-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rfc_register_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfc_register',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
