# Generated by Django 4.2.7 on 2024-05-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_rfc_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfc_register',
            name='status',
            field=models.CharField(default='pending', max_length=100, null=True),
        ),
    ]
