# Generated by Django 4.2.7 on 2024-05-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_rfc_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfc_register',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
